apiVersion: v1
kind: Service
metadata:
  #The name of the Kubernetes Service to be created
  #in the Kubernetes cluster
  name: jenkins-test
spec:
  selector:
    app: jenkins-test
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
    - protocol: TCP
      port: 3000 #Service port
      targetPort: 3000 #The port for the React.js application container
